services:
  api:
    ports:
      - 3001:3001
    container_name: aws_api
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=Aula*Infra
      - DB_DATABASE=aws_db
      - DB_HOST=aws-db-ativ.csjlwegrg9nd.us-east-1.rds.amazonaws.com
    build:
      context: ./backend  
      dockerfile: Dockerfile

  frontend:
    ports:
      - 3000:80  
    container_name: aws_frontend
    build:
      context: ./frontend  
      dockerfile: Dockerfile